[build]
publish = "public"
command = "hugo --gc --minify -b ${DEPLOY_PRIME_URL}"

[build.environment]
HUGO_VERSION = "0.132.2"
DEPLOY_PRIME_URL = "https://repronim.org"

[[redirects]]
  from = "/module-intro/*"
  to = "https://legacy.repronim.org/module-intro/:splat"
  status = 301
  force = true
