[build]
publish = "public"
command = "hugo --gc --minify -b ${DEPLOY_PRIME_URL}"

[build.environment]
HUGO_VERSION = "0.132.2"
DEPLOY_PRIME_URL = "https://repronim.org"


[[redirects]]
  from = "/brainhack_ohbm18/*"
  to = "https://legacy.repronim.org/brainhack_ohbm18/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/coco2019-training/*"
  to = "https://legacy.repronim.org/coco2019-training/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/demo-protocol/*"
  to = "https://legacy.repronim.org/demo-protocol/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/DGPA_workshop_2022/*"
  to = "https://legacy.repronim.org/DGPA_workshop_2022/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/metasearch/*"
  to = "https://legacy.repronim.org/metasearch/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/module-dataprocessing/*"
  to = "https://legacy.repronim.org/module-dataprocessing/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/module-FAIR-data/*"
  to = "https://legacy.repronim.org/module-FAIR-data/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/module-intro/*"
  to = "https://legacy.repronim.org/module-intro/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/module-reproducible-basics/*"
  to = "https://legacy.repronim.org/module-reproducible-basics/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/module-stats/*"
  to = "https://legacy.repronim.org/module-stats/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/module-template/*"
  to = "https://legacy.repronim.org/module-template/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/neurodocker/*"
  to = "https://legacy.repronim.org/neurodocker/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/nimh-minimal/*"
  to = "https://legacy.repronim.org/nimh-minimal/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ohbm2018-training/*"
  to = "https://legacy.repronim.org/ohbm2018-training/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/OHBMEducation-2022/*"
  to = "https://legacy.repronim.org/OHBMEducation-2022/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/ReproInventory/*"
  to = "https://legacy.repronim.org/ReproInventory/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/reproschema/*"
  to = "https://legacy.repronim.org/reproschema/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/reproschema-demo/*"
  to = "https://legacy.repronim.org/reproschema-demo/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/reproschema-demo-protocol/*"
  to = "https://legacy.repronim.org/reproschema-demo-protocol/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/reproschema-ui/*"
  to = "https://legacy.repronim.org/reproschema-ui/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/sfn2018-training/*"
  to = "https://legacy.repronim.org/sfn2018-training/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/SOBPHack-042025/*"
  to = "https://legacy.repronim.org/SOBPHack-042025/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/SOBPHack-052024/*"
  to = "https://legacy.repronim.org/SOBPHack-052024/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/5Steps/*"
  to = "https://legacy.repronim.org/5Steps/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/2019_training_logistics.html"
  to = "https://legacy.repronim.org/2019_training_logistics.html"
  status = 301
  force = true

[[redirects]]
  from = "/5steps.html"
  to = "https://legacy.repronim.org/5steps.html"
  status = 301
  force = true

[[redirects]]
  from = "/about_us.html"
  to = "https://legacy.repronim.org/about_us.html"
  status = 301
  force = true

[[redirects]]
  from = "/collaborators.html"
  to = "https://legacy.repronim.org/collaborators.html"
  status = 301
  force = true

[[redirects]]
  from = "/community.html"
  to = "https://legacy.repronim.org/community.html"
  status = 301
  force = true

[[redirects]]
  from = "/describe.html"
  to = "https://legacy.repronim.org/describe.html"
  status = 301
  force = true

[[redirects]]
  from = "/discover.html"
  to = "https://legacy.repronim.org/discover.html"
  status = 301
  force = true

[[redirects]]
  from = "/do.html"
  to = "https://legacy.repronim.org/do.html"
  status = 301
  force = true

[[redirects]]
  from = "/eab.html"
  to = "https://legacy.repronim.org/eab.html"
  status = 301
  force = true

[[redirects]]
  from = "/events.html"
  to = "https://legacy.repronim.org/events.html"
  status = 301
  force = true

[[redirects]]
  from = "/fellows-resources.html"
  to = "https://legacy.repronim.org/fellows-resources.html"
  status = 301
  force = true

[[redirects]]
  from = "/fellowship.html"
  to = "https://legacy.repronim.org/fellowship.html"
  status = 301
  force = true

[[redirects]]
  from = "/how-would-repronim.html"
  to = "https://legacy.repronim.org/how-would-repronim.html"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "https://legacy.repronim.org/index.html"
  status = 301
  force = true

[[redirects]]
  from = "/news_archive.html"
  to = "https://legacy.repronim.org/news_archive.html"
  status = 301
  force = true

[[redirects]]
  from = "/publications.html"
  to = "https://legacy.repronim.org/publications.html"
  status = 301
  force = true

[[redirects]]
  from = "/search.html"
  to = "https://legacy.repronim.org/search.html"
  status = 301
  force = true

[[redirects]]
  from = "/teach.html"
  to = "https://legacy.repronim.org/teach.html"
  status = 301
  force = true

[[redirects]]
  from = "/template.html"
  to = "https://legacy.repronim.org/template.html"
  status = 301
  force = true

[[redirects]]
  from = "/use_cases.html"
  to = "https://legacy.repronim.org/use_cases.html"
  status = 301
  force = true

[[redirects]]
  from = "/webinar-series.html"
  to = "https://legacy.repronim.org/webinar-series.html"
  status = 301
  force = true

[[redirects]]
  from = "/Training/*"
  to = "https://legacy.repronim.org/Training/:splat"
  status = 301
  force = true
