[project]
name = "repronim-publications"
version = "0.1.0"
description = "Scripts for generating ReproNim publications from DOIs"
requires-python = ">=3.10"
dependencies = [
    "citeproc-py[full]>=0.9.0",
    "pyyaml>=6.0",
    "duecredit>=0.9.0",
]
