name: Check Links
on:
  pull_request: {}


jobs:
  build-and-test-links:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # If your Hugo theme is a submodule, this ensures it gets pulled
          submodules: true

      - name: Install linkchecker
        run: |
          pip install linkchecker

      - name: Read hugo version
        id: hugo-version
        run: |
          HUGO_VERSION=$(grep 'HUGO_VERSION' netlify.toml | sed -E 's/.*=\s*"([^"]+)".*/\1/')
          echo ${HUGO_VERSION}
          echo "HUGO_VERSION=${HUGO_VERSION}" >> "${GITHUB_OUTPUT}"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '${{ steps.hugo-version.outputs.HUGO_VERSION }}'

      - name: Build site
        run: |
          hugo
          # linkchecker will skip if we do not remove robots tags
          sed -i '/<meta name="robots"/d' public/**/*.html
          cd public
          # Simple server not hugo so autoreload does not confuse linkchecker
          python3 -m http.server 1313 &
          sleep 1

      - name: Check links
        run: |
          linkchecker --check-extern -f .linkcheckerrc http://localhost:1313
